name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack Typezor.SourceGenerator
      run: dotnet pack Typezor.SourceGenerator/Typezor.SourceGenerator.csproj --output nuget-packages --configuration Release
    - name: Pack Typezor.Runtime
      run: dotnet pack Typezor.Runtime/Typezor.Runtime.csproj --output nuget-packages --configuration Release
    - name: Pack Typezor.CodeModel
      run: dotnet pack src/CodeModel/Typezor.CodeModel.csproj --output nuget-packages --configuration Release
    - name: Push Nuget packages
      run: dotnet nuget push **/*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/ReactiveThings/index.json
